import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
//任何需要身份验证状态的组件
import { useAuth } from '../lib/auth';

export default function Index() {
  //获取身份验证状态并在其更改时重新渲染
  const auth = useAuth();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Fast Feedback</h1>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        {/* 用户授权为true则读取并显示用户email,button显示“sign out” */}
        {auth.user ? (
          <div>
            <p>Email: {auth.user.email}</p>
            {/* 点击按钮调用signout函数清理用户数据 */}
            <button onClick={() => auth.signout()}>Sign Out</button>
          </div>
        ) : (
          //点击按钮调用signinWithGitHub函数读取用户数据
          <button onClick={() => auth.signinWithGitHub()}>Sign In</button>
        )}
        {/* <button onClick={(e) => auth().signinWithGithub()}>Sign In</button>
        <div>{auth?.user?.email}</div>
        {auth?.user && (
          <button onClick={(e) => auth().signout()}>Sign Out</button>
        )} */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
